django_2fa/urls.py
from django.urls import path

import django_2fa.views as mfa_views
import django_2fa.views_api as mfa_api_views
from django_2fa.apps import Django2FaConfig


app_name = Django2FaConfig.name

urlpatterns = [
  path('test/', mfa_views.test_2fa, name='test'),
  path('login/verify/<str:device>/', mfa_views.login_2fa_verify, name='verify'),
  path('login/', mfa_views.login_2fa, name='login'),
  path('login/external/json', mfa_api_views.ext_login, name='external-login'),

  path('request/<str:token>/', mfa_views.mfa_request, name='mfa-request'),
  path('request-complete/<str:token>/', mfa_views.mfa_request_complete, name='mfa-request-complete'),
  path('request-use/<str:token>/', mfa_api_views.request_use, name='mfa-request-use'),

  path('devices/', mfa_views.devices_list, name='devices'),
  path('devices/json', mfa_views.devices_list, name='devices-json', kwargs={'response_type': 'json'}),

  path('devices/add/', mfa_views.device_add, name='device-add'),
  path('devices/add/json', mfa_views.device_add_json, name='device-add-json'),

  path('devices/<str:device>/remove/', mfa_views.device_remove, name='device-remove'),
  path('devices/<str:device>/remove/json', mfa_views.device_remove, name='device-remove-json', kwargs={'response_type': 'json'}),

  path('devices/<str:device>/complete/', mfa_views.device_complete, name='device-complete'),
  path('devices/<str:device>/complete/json', mfa_views.device_complete_json, name='device-complete-json'),

  path('fido/<str:device>/reg-begin/', mfa_api_views.register_begin, name='fido-reg-begin'),
  path('fido/<str:device>/reg-complete/', mfa_api_views.register_complete, name='fido-reg-complete'),
  path('fido/<str:device>/auth-begin/', mfa_api_views.authenticate_begin, name='fido-auth-begin'),
  path('fido/<str:device>/auth-complete/', mfa_api_views.authenticate_complete, name='fido-auth-complete'),
]

django_2fa/models.py
import datetime

from django.conf import settings
from django.core.mail import send_mail
from django.db import models
from django.template.loader import render_to_string
from django.utils import timezone

import jwt
import pyotp
from encrypted_fields.fields import EncryptedTextField
from haikunator import Haikunator

import django_2fa.settings as mfa_settings


class Device(models.Model):
  DEVICE_TYPES = (
    ('email', 'E-Mail'),
    ('app', 'Authenicator App'),
    ('hkey', 'Hardware Key'),
  )

  name = models.CharField(max_length=64)
  device_type = models.CharField(max_length=10, choices=DEVICE_TYPES)
  secret = EncryptedTextField(blank=True, null=True)
  counter = models.PositiveIntegerField(default=0)
  counter_expire = models.DateTimeField(blank=True, null=True)
  setup_complete = models.BooleanField(default=False)

  owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

  created = models.DateTimeField(auto_now_add=True)

  class Meta:
    unique_together = [['name', 'owner']]

  def __str__(self):
    return self.name

  def to_dict(self):
    return {
      'id': self.id,
      'name': self.name,
      'device_type': self.device_type,
      'setup_complete': self.setup_complete,
      'setup_url': self.setup_url,
      'created': self.created.isoformat(),
    }

  def verify_code(self, code):
    if self.device_type == 'email':
      now = timezone.now()
      if self.counter_expire and now <= self.counter_expire:
        hotp = pyotp.HOTP(self.secret)
        return hotp.verify(code, self.counter)

    elif self.device_type == 'app':
      totp = pyotp.TOTP(self.secret)
      return totp.verify(code)

    return False

  @property
  def setup_url(self):
    if not self.setup_complete and self.device_type == 'app':
      return self.provision_url

  @property
  def provision_url(self):
    totp = pyotp.totp.TOTP(self.secret)
    return totp.provisioning_uri(name=f"User-{self.owner.id}", issuer_name=mfa_settings.MFA_ISSUER_NAME)

  def send_code(self):
    self.counter += 1
    self.counter_expire = timezone.now() + datetime.timedelta(minutes=15)
    self.save()

    hotp = pyotp.HOTP(self.secret)
    code = hotp.at(self.counter)

    context = {'device': self, 'code': code}
    txt_message = render_to_string('2fa/email-code.txt', context)
    html_message = render_to_string('2fa/email-code.html', context)

    send_mail(
      mfa_settings.MFA_EMAIL_SUBJECT,
      txt_message,
      settings.DEFAULT_FROM_EMAIL,
      [self.owner.email],
      html_message=html_message,
      fail_silently=False,
    )


class MFARequest(models.Model):
  slug = models.SlugField(max_length=75)
  owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
  completed = models.BooleanField(default=False)
  used = models.BooleanField(default=False)

  created = models.DateTimeField(auto_now_add=True)

  def __str__(self):
    return self.slug


  @property
  def token(self):
    encoded_jwt = jwt.encode(
      {
        "slug": self.slug,
        "exp": timezone.now() + datetime.timedelta(minutes=mfa_settings.MFA_TOKEN_EXPIRE)
      },
      settings.SECRET_KEY,
      algorithm="HS256"
    )
    return encoded_jwt

  @classmethod
  def generate(cls, user):
    haikunator = Haikunator()

    while 1:
      slug = haikunator.haikunate(token_length=5)
      request = cls(slug=slug, owner=user)

      try:
        request.save()

      except:
        continue

      else:
        return request

  @classmethod
  def get_from_token(cls, token, owner=None, completed=False):
    data = jwt.decode(token, settings.SECRET_KEY, algorithms=["HS256"])

    kwargs = {
      'slug': data['slug'],
      'completed': completed,
      'used': False,
    }
    if owner:
      kwargs['owner'] = owner

    return cls.objects.get(**kwargs)

django_2fa/templates/2fa/add-device.html
{% extends "2fa/base.html" %}{% load i18n %}
{% block title %}{% translate "Add 2nd Factor Device" %}{% endblock %}
{% block nav-title %}
<h1>{% translate "Add 2nd Factor Device" %}</h1>
{% endblock %}
{% block content %}
<div class="row">
  {% if form.errors and not form.non_field_errors %}
  <p class="errornote">
  {% if form.errors.items|length == 1 %}{% translate "Please correct the error below." %}{% else %}{% translate "Please correct the errors below." %}{% endif %}
  </p>
  {% endif %}
  <form action="{{ request.path }}" method="post" id="add-device-form" class="col s12">
    {% csrf_token %}
    <input type="hidden" name="{{ next_field }}" value="{{ next }}">
    {% if form.non_field_errors %}
    <div class="form-row">
      {{ form.non_field_errors }}
    </div>
    {% endif %}
    <div class="row">
      <div class="input-field col s12 l6">
        {{ form.name.errors }}
        {{ form.name }}
        {{ form.name.label_tag }}
      </div>
    </div>
    <div class="row">
      <div class="input-field col s12 l6">
        {{ form.device_type.errors }}
        {{ form.device_type }}
        {{ form.device_type.label_tag }}
      </div>
    </div>
    {% for hidden in form.hidden_fields %}{{ hidden }}{% endfor %}
    <div class="row">
      <div class="input-field col s12 l6">
        <button class="btn waves-effect waves-light" type="submit">
          {% translate 'Continue' %}
        </button>
      </div>
    </div>
  </form>
</div>
{% endblock %}
{% block script %}
{{ block.super }}
<script>
  document.addEventListener('DOMContentLoaded', function() {
    var elems = document.querySelectorAll('select');
    var instances = M.FormSelect.init(elems);
  });
</script>
{% endblock %}

django_2fa/templates/2fa/base.html
<!doctype html>
<html lang="en">
<head>
  {% block meta %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="//fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
  <style>
    nav .nav-wrapper {
      display: flex;
      align-items: center;
    }

    nav .nav-wrapper h1 {
      margin: 0;
      font-size: 1.8rem;
      font-weight: bold;
    }

    .errorlist {
      color: red;
    }

    .tc {
      text-align: center;
    }
  </style>
  {% endblock %}
  <title>{% block title %}{% endblock %}</title>
</head>
<body>
  {% block nav %}
  <nav class="blue lighten-1" role="navigation">
    <div class="nav-wrapper container">
      {% block nav-title %}{% endblock %}
    </div>
  </nav>
  {% endblock %}
  {% block content-wrapper %}
  <div class="section no-pad-bot">
    <div class="container">
      {% block content %}{% endblock %}
    </div>
  </div>
  {% endblock %}
  {% block script %}
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
  {% endblock %}
</body>
</html>

django_2fa/templates/2fa/complete-fido.html
{% extends "2fa/base.html" %}{% load i18n static %}
{% block title %}{% translate "2nd Factor Login" %}{% endblock %}
{% block nav-title %}
<h1>{% translate 'Hardware Key Setup' %}</h1>
{% endblock %}
{% block content %}
<div id="content-main">
  <h4 class="tc">{% translate 'Insert your hardware key to complete setup for:' %} {{ device.name }}</h4>
</div>
{% endblock %}
{% block script %}
{{ block.super }}
<script src="{% static '2fa/axios.min.js' %}"></script>
<script src="{% static '2fa/cbor.js' %}"></script>
<script>
function start_reg() {
  axios.post("{% url 'django_2fa:fido-reg-begin' device.id %}", {}, {responseType: 'arraybuffer'})
    .then((response) => {
      return CBOR.decode(response.data);
    })
    .then((options) => {
      return navigator.credentials.create(options);
    })
    .then((attestation) => {
      var data = CBOR.encode({
        "attestationObject": new Uint8Array(attestation.response.attestationObject),
        "clientDataJSON": new Uint8Array(attestation.response.clientDataJSON)
      });
      return axios.post("{% url 'django_2fa:fido-reg-complete' device.id %}", data, {});
    })
    .then((response) => {
      location.href = "{{ next }}";
    })
    .catch((e) => {
      console.error(e);
      alert('{% translate "Error in hardware key registration" %}');
    });
}

start_reg();
</script>
{% endblock %}

django_2fa/templates/2fa/devices.html
{% extends "2fa/base.html" %}{% load i18n %}
{% block title %}{% translate "2nd Factor Device List" %}{% endblock %}
{% block nav-title %}
<h1>{% translate "2nd Factor Devices" %}</h1>
{% endblock %}
{% block content %}
<div id="content-main">
  <a href="{% url 'django_2fa:device-add' %}" class="waves-effect waves-light btn">
    Add Device
  </a>
  <ul class="collection">
    {% for d in devices %}
    <li class="collection-item avatar">
      <i class="material-icons circle">
        {% if d.device_type == 'email' %}mail
        {% elif d.device_type == 'app' %}phone_android
        {% else %}vpn_key{% endif %}
      </i>
      <span class="title">
        <strong>{{ d.name }} - {{ d.get_device_type_display }}</strong>
      </span>
      <p>
        {% if not d.setup_complete %}
        <a href="{% url 'django_2fa:device-complete' d.id %}">Complete Setup</a><br>
        {% endif %}
        Added: {{ d.created|date:"D, dS M Y" }}
      </p>
      <a href="{% url 'django_2fa:device-remove' d.id %}" title="remove" class="secondary-content" onclick="return confirm('Are sure you wish to remove this device?')">
        <i class="material-icons">delete</i>
      </a>
    </li>
    {% endfor %}
  </ul>
</div>
{% endblock %}

django_2fa/templates/2fa/email-code.html
<!DOCTYPE html>{% load i18n %}
<html lang="en" xmlns="http://www.w3.org/1999/xhtml" xmlns:o="urn:schemas-microsoft-com:office:office">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <title></title>
</head>
<body>
  <h1>
    {% translate 'Temporary Authorization Code' %}
  </h1>
  <p>
    {% translate 'Code:' %} {{ code }}
  </p>
</body>
</html>

django_2fa/templates/2fa/login.html
{% extends "2fa/base.html" %}{% load i18n %}
{% block title %}{% translate "2nd Factor Login" %}{% endblock %}
{% block nav-title %}
<h1>{% translate "Choose a device to verify your login:" %}</h1>
{% endblock %}
{% block content %}
<div id="row">
  <ul class="collection">
    {% for d in devices %}
    <li class="collection-item avatar">
      <a href="{% url 'django_2fa:verify' d.id %}?{{ next_field }}={{ next|urlencode }}">
        <i class="material-icons circle">
          {% if d.device_type == 'email' %}mail
          {% elif d.device_type == 'app' %}phone_android
          {% else %}vpn_key{% endif %}
        </i>
      </a>
      <span class="title">
        <strong>
          <a href="{% url 'django_2fa:verify' d.id %}?{{ next_field }}={{ next|urlencode }}">{{ d.name }}</a>
        </strong>
      </span>
    </li>
    {% endfor %}
  </ul>
</div>
{% endblock %}

django_2fa/templates/2fa/request-completed.html
{% extends "2fa/base.html" %}{% load i18n %}
{% block title %}{% translate "2nd Factor Verified" %}{% endblock %}
{% block nav-title %}
<h1>{% translate "2nd Factor Verified" %}</h1>
{% endblock %}
{% block content %}
<div class="row">
  <h3>{% translate "Your 2nd Factor has been verified." %}</h3>
  <h3>{% translate "You may now continue in your application." %}</h3>
</div>
{% endblock %}

django_2fa/templates/2fa/verify-fido.html
{% extends "2fa/base.html" %}{% load i18n static %}
{% block title %}{% translate "2nd Factor Login" %}{% endblock %}
{% block nav-title %}
<h1>{% translate 'Hardware Key Verification' %}</h1>
{% endblock %}
{% block content %}
<div id="content-main">
  <h4 class="tc">{% translate 'Use your hardware key to continue.' %}</h4>
</div>
{% endblock %}
{% block script %}
{{ block.super }}
<script src="{% static '2fa/axios.min.js' %}"></script>
<script src="{% static '2fa/cbor.js' %}"></script>
<script>
function start_auth() {
  axios.post("{% url 'django_2fa:fido-auth-begin' device.id %}", {}, {responseType: 'arraybuffer'})
    .then((response) => {
      return CBOR.decode(response.data);
    })
    .then((options) => {
      return navigator.credentials.get(options);
    })
    .then((assertion) => {
      var data = CBOR.encode({
        "credentialId": new Uint8Array(assertion.rawId),
        "authenticatorData": new Uint8Array(assertion.response.authenticatorData),
        "clientDataJSON": new Uint8Array(assertion.response.clientDataJSON),
        "signature": new Uint8Array(assertion.response.signature)
      });
      return axios.post("{% url 'django_2fa:fido-auth-complete' device.id %}", data, {});
    })
    .then((response) => {
      location.href = "{{ next }}";
    })
    .catch((e) => {
      console.error(e);
      alert('{% translate "Error in hardware key authorization" %}');
    });
}

start_auth();
</script>
{% endblock %}

django_2fa/templates/2fa/verify.html
{% extends "2fa/base.html" %}{% load i18n static %}
{% block title %}{% translate "2nd Factor Login" %}{% endblock %}
{% block nav-title %}
{% if complete_setup %}
<h1>{% translate 'Verify your authorization device.' %}</h1>
{% else %}
<h1>{% translate 'Authorization Code Required' %}</h1>
{% endif %}
{% endblock %}
{% block content %}
{% if form.errors and not form.non_field_errors %}
<p class="errornote">
{% if form.errors.items|length == 1 %}{% translate "Please correct the error below." %}{% else %}{% translate "Please correct the errors below." %}{% endif %}
</p>
{% endif %}
<div class="row">
  <form action="{{ request.path }}" method="post" id="mfa-form" class="col s12">
    {% csrf_token %}
    <input type="hidden" name="{{ next_field }}" value="{{ next }}">
    {% if form.non_field_errors %}
    <div class="form-row">
      {{ form.non_field_errors }}
    </div>
    {% endif %}
    <div class="row">
      <p>
        <strong>{% translate 'Authenticator:' %} {{ device.name }}</strong><br>
        {% if device.device_type == 'email' %}
        {% translate 'Check your e-mail for your authorization code.' %}
        {% elif device.device_type == 'app' %}
        {% if not complete_setup %}{% translate 'Enter code from your authenicator application.' %}{% endif %}
        {% else %}
        {% translate 'Use your hardware token to complete sign in.' %}
        {% endif %}
      </p>
    </div>
    <div class="row">
      {% if complete_setup and device.device_type == 'app' %}
      <p>
        {% translate 'Scan QR below in your authenicator app, then enter a code to verify your device.' %}
        <br>
        <canvas id="qr"></canvas>
        <br><br><strong>{% translate 'Provision URL:' %}</strong><br>
        <pre>{{ device.provision_url }}</pre>
      </p>
      {% endif %}
      <div class="input-field col s12 l6">
        {{ form.mfa_code.errors }}
        {{ form.mfa_code }}
        {{ form.mfa_code.label_tag }}
      </div>
    </div>
    <div class="row">
      <div class="input-field col s12 l6">
        <button class="btn waves-effect waves-light" type="submit">{% translate 'Continue' %}</button>
      </div>
    </div>
  </form>
</div>
{% endblock %}
{% block script %}
{{ block.super }}
{% if complete_setup and device.device_type == 'app' %}
<script src="{% static '2fa/qrious.min.js' %}"></script>
<script>
  (function() {
    var qr = new QRious({
      element: document.getElementById('qr'),
      value: '{{ device.provision_url }}',
      size: 200
    });
  })();
</script>
{% endif %}
{% endblock %}